env: dev
project_name: partner-master-service
namespace: dev-thea
fqdn: '{{ env }}\.(app|wms|thea|arsenal|vault|hustler|store)\.scm\.gomercury\.in'
route: /api/partner/
tag: '{{ env }}-{{ build_number }}'
context: scm-staging-eks
profile: gomercury
account_no: 774391698360
min_replicas: 1
max_replicas: 1
role_arn: arn:aws:iam::774391698360:role/K8sS3ServiceAccount
requests_cpu: 0.3
requests_memory: 512Mi
limits_cpu: 2.0
limits_memory: 2048Mi
configmap:
  HOST: mysql-dev.scm.gomercury.in
  DATABASE: partner
  PORT: '3306'
config_map_yaml: "application.yml: |-\n  transaction-outbox:\n    kafka-bootstrap-servers:\
  \ kafka.scm.gomercury.in:9092\n  logging.level.com.pharmeasy: DEBUG\n  keycloak.credentials.secret:\
  \ ${KEYCLOAK_SECRET}\n  app:\n    product:\n      url: https://stage-catalog-api-gateway.dev.pharmeasy.in\n\
  \      auth: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJzYWx0Ijo4ODgwNTR9.sqm8KlNegUpv2yH17vt3y8LET1HBCXkR8g69FB5ilyE'\n\
  \    draftUrl: https://qa.hustler.gomercury.in/master-data/partner-master/drafts?partnerDraftId=\n\
  \    checker_email_list: vishal.daga@pharmeasy.in\n    keys:\n      scm:\n     \
  \   public: ${PUBLIC_SCM_KEY}\n        private: ${PRIVATE_SCM_KEY}\n      rio:\n\
  \        public: ${PUBLIC_RIO_KEY}\n  spring:\n    cache:\n      type: caffeine\n\
  \    profile: {{ env }}\n    cloud:\n      stream:\n        bindings:\n        \
  \  retailerTheaMappingUpdate:\n            destination: {{ env }}_retailer_thea_mapping_update\n\
  \            producer:\n              partitionKeyExpression: payload.partnerDetailId\n\
  \              partitionCount: 3\n          retailerUpdate:\n            destination:\
  \ {{ env }}_retailer_update\n          productMappingUpdate:\n            destination:\
  \ {{ env }}_product_mapping_update\n          onUploadProductMappingFile:\n    \
  \        destination: {{ env }}_upload_product_mapping\n          partnerBlockedUpdate:\n\
  \            destination : {{ env }}_partner_blocked_update\n          processPartnerBlockedEvent:\n\
  \            destination: {{ env }}_partner_blocked_update\n            group: dev-partner-master-service\n\
  \          vendorPortalContactCreationUpdate:\n            destination: {{ env }}_vendor_portal_contact_creation\n\
  \          sendNotification:\n            destination: {{ env }}_notify\n      \
  \      producer:\n              partitionCount: 18\n            group: mco-partner-master-service\n\
  \          partnerGenericCacheWarmupSenderV2:\n            destination: {{ env }}_partner_generic_cache_warmup_v2\n\
  \          partnerGenericCacheWarmupReceiverV2:\n            destination: {{ env\
  \ }}_partner_generic_cache_warmup_v2\n            group: mco-partner-master-service\n\
  \          partnerGenericCacheWarmupSender:\n            destination: {{ env }}_partner_generic_cache_warmup\n\
  \          partnerGenericCacheWarmupReceiver:\n            destination: {{ env }}_partner_generic_cache_warmup\n\
  \            group: mco-partner-master-service\n          retailerInfoCacheWarmUp:\n\
  \            destination: {{ env}}_retailer_info_cache_warmup\n          onRetailerInfoCacheWarmUp:\n\
  \            destination: {{ env}}_retailer_info_cache_warmup\n            group:\
  \ mco-partner-master-service\n          partnerManufacturerListDownloadSource:\n\
  \            destination: {{ env}}_partner_manufacturer_list_download\n        \
  \  partnerManufacturerListDownloadSink:\n            destination: {{ env}}_partner_manufacturer_list_download\n\
  \            group: mco-partner-master-service\n          manufacturerSyncHandler:\n\
  \            destination: {{ env }}_manufacturer_sync_new\n            group: mco-partner-master-service\n\
  \          manufacturerSyncTrigger:\n            destination: {{ env }}_manufacturer_sync_new\n\
  \            group: mco-partner-master-service\n          partnerManufacturerUploadTrigger:\n\
  \            destination: {{ env }}_partner_manufacturer_upload\n            group:\
  \ mco-partner-master-service\n          partnerManufacturerUploadHandler:\n    \
  \        destination: {{ env }}_partner_manufacturer_upload\n            group:\
  \ mco-partner-master-service\n          sellerPortalPartnerExternalUpdate:\n   \
  \         destination: {{ env }}_seller_portal_partner_external_update\n       \
  \   sellerPortalPartnerExternalUpdateResponse:\n            destination: {{ env\
  \ }}_seller_portal_partner_external_update_response\n          triggerPartnerDraftApprovalRequest:\n\
  \            destination: {{ env }}_partner_draft_approval_request\n          partnerExternalUpdate:\n\
  \            destination: {{ env }}_partner_external_update\n          partnerExternalUpdateResponse:\n\
  \            destination: {{ env }}_partner_external_update_response\n         \
  \ triggerPartnerDraftDedup:\n            destination: {{ env }}_partner_dedup_queue\n\
  \            producer:\n              partitionKeyExpression: payload.partnerDraftId\n\
  \              partitionCount: 1\n          triggerPartnerAutoApproval:\n      \
  \      destination: {{ env }}_partner_auto_approval\n          triggerPickupAddressUpdateEvent:\n\
  \            destination: {{ env }}_pickup_address_update  \n          processAutoApprovalRequest:\n\
  \            destination: {{ env }}_partner_auto_approval\n            group: mco-partner-master-service\n\
  \          processPartnerDraftDedup:\n            destination: {{ env }}_partner_dedup_queue\n\
  \          subDivisionSync:\n            destination: {{ env}}_license_sub_division_sync\n\
  \            group: mco-partner-master-service\n          onSubDivisionSync:\n \
  \           destination: {{ env}}_license_sub_division_sync\n            group:\
  \ mco-partner-master-service\n          expiringLicensePartnersEvent:\n        \
  \    destination: {{ env }}_expiring_license_partners\n          processExpiringLicensePartnersEvent:\n\
  \            destination: {{ env }}_expiring_license_partners\n            group:\
  \ mco-partner-master-service\n          triggerInMemoryCacheEvictEvent:\n      \
  \      destination: {{ env }}_in_memory_cache_evict\n          processInMemoryCacheEvictEvent:\n\
  \            destination: {{ env }}_in_memory_cache_evict\n          triggerRefreshPartnerWhPoMappingEvent:\n\
  \            destination: {{ env }}_refresh_partner_wh_po_mapping\n          processRefreshPartnerWhPoMappingEvent:\n\
  \            destination: {{ env }}_refresh_partner_wh_po_mapping\n            group:\
  \ mco-partner-master-service\n          triggerSellerContactDetailUpdateEvent:\n\
  \            destination: {{ env }}_seller_location_contact_mapping_update\n   \
  \     kafka:\n          binder:\n            brokers: kafka.scm.gomercury.in:9092\n\
  \    datasource:\n      hikari:\n        jdbc-url: jdbc:mysql://mysql-dev.scm.gomercury.in:3306/partner?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true\n\
  \        password: ${DB_PASS}\n        username: ${DB_USER}\n      url: jdbc:mysql://mysql-dev.scm.gomercury.in:3306/partner?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true\n\
  \    jpa:\n      show-sql: false\n    redis:\n      host: redis-dev.redis.svc.cluster.local\n\
  \      port: 6379\n      database: 1\n      connection-timeout: 500\n    openapi:\n\
  \      server:\n        url: {{ fqdn }}/{{ project_name }}\n        description:\
  \ Development\n    springdoc:\n      api-docs:\n        path: /api-docs"
