env: dev
project_name: partner-master-service
namespace: dev-thea
fqdn: "{{ env }}\\.(app|wms|thea|arsenal|vault|hustler|store)\\.scm\\.gomercury\\.in"
route: "/api/partner/"
tag: "{{ env }}-{{ build_number }}"
context: scm-staging-eks
profile: gomercury
account_no: 774391698360
min_replicas: 1
max_replicas: 1
role_arn: arn:aws:iam::774391698360:role/K8sS3ServiceAccount
requests_cpu: 0.3
requests_memory: 512Mi
limits_cpu: 2.0
limits_memory: 2048Mi
configmap:
  HOST: "mysql-dev.scm.gomercury.in"
  DATABASE: "partner"
  PORT: "3306"
config_map_yaml: |-
  application.yml: |-

  openapis:
    servesr:
      url: {{ fqdns }}/{{ project_name }}
      descriptions: Development
  springdocs:
    api-docss:
      path: /api-docss
    transaction-outbox:
      kafka-bootstrap-servers: kafka.scm.gomercury.in:9092
    logging.level.com.pharmeasy: DEBUG
    keycloak.credentials.secret: ${KEYCLOAK_SECRET}
    app:
      product:
        url: https://stage-catalog-api-gateway.dev.pharmeasy.in
        auth: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJzYWx0Ijo4ODgwNTR9.sqm8KlNegUpv2yH17vt3y8LET1HBCXkR8g69FB5ilyE'
      draftUrl: https://qa.hustler.gomercury.in/master-data/partner-master/drafts?partnerDraftId=
      checker_email_list: vishal.daga@pharmeasy.in
      keys:
        scm:
          public: ${PUBLIC_SCM_KEY}
          private: ${PRIVATE_SCM_KEY}
        rio:
          public: ${PUBLIC_RIO_KEY}
    spring:
      cache:
        type: caffeine
      profile: {{ env }}
      cloud:
        stream:
          bindings:
            retailerTheaMappingUpdate:
              destination: {{ env }}_retailer_thea_mapping_update
              producer:
                partitionKeyExpression: payload.partnerDetailId
                partitionCount: 3
            retailerUpdate:
              destination: {{ env }}_retailer_update
            productMappingUpdate:
              destination: {{ env }}_product_mapping_update
            onUploadProductMappingFile:
              destination: {{ env }}_upload_product_mapping
            partnerBlockedUpdate:
              destination : {{ env }}_partner_blocked_update
            processPartnerBlockedEvent:
              destination: {{ env }}_partner_blocked_update
              group: dev-partner-master-service
            vendorPortalContactCreationUpdate:
              destination: {{ env }}_vendor_portal_contact_creation
            sendNotification:
              destination: {{ env }}_notify
              producer:
                partitionCount: 18
              group: mco-partner-master-service
            partnerGenericCacheWarmupSenderV2:
              destination: {{ env }}_partner_generic_cache_warmup_v2
            partnerGenericCacheWarmupReceiverV2:
              destination: {{ env }}_partner_generic_cache_warmup_v2
              group: mco-partner-master-service
            partnerGenericCacheWarmupSender:
              destination: {{ env }}_partner_generic_cache_warmup
            partnerGenericCacheWarmupReceiver:
              destination: {{ env }}_partner_generic_cache_warmup
              group: mco-partner-master-service
            retailerInfoCacheWarmUp:
              destination: {{ env}}_retailer_info_cache_warmup
            onRetailerInfoCacheWarmUp:
              destination: {{ env}}_retailer_info_cache_warmup
              group: mco-partner-master-service
            partnerManufacturerListDownloadSource:
              destination: {{ env}}_partner_manufacturer_list_download
            partnerManufacturerListDownloadSink:
              destination: {{ env}}_partner_manufacturer_list_download
              group: mco-partner-master-service
            manufacturerSyncHandler:
              destination: {{ env }}_manufacturer_sync_new
              group: mco-partner-master-service
            manufacturerSyncTrigger:
              destination: {{ env }}_manufacturer_sync_new
              group: mco-partner-master-service
            partnerManufacturerUploadTrigger:
              destination: {{ env }}_partner_manufacturer_upload
              group: mco-partner-master-service
            partnerManufacturerUploadHandler:
              destination: {{ env }}_partner_manufacturer_upload
              group: mco-partner-master-service
            sellerPortalPartnerExternalUpdate:
              destination: {{ env }}_seller_portal_partner_external_update
            sellerPortalPartnerExternalUpdateResponse:
              destination: {{ env }}_seller_portal_partner_external_update_response
            triggerPartnerDraftApprovalRequest:
              destination: {{ env }}_partner_draft_approval_request
            partnerExternalUpdate:
              destination: {{ env }}_partner_external_update
            partnerExternalUpdateResponse:
              destination: {{ env }}_partner_external_update_response
            triggerPartnerDraftDedup:
              destination: {{ env }}_partner_dedup_queue
              producer:
                partitionKeyExpression: payload.partnerDraftId
                partitionCount: 1
            triggerPartnerAutoApproval:
              destination: {{ env }}_partner_auto_approval
            triggerPickupAddressUpdateEvent:
              destination: {{ env }}_pickup_address_update  
            processAutoApprovalRequest:
              destination: {{ env }}_partner_auto_approval
              group: mco-partner-master-service
            processPartnerDraftDedup:
              destination: {{ env }}_partner_dedup_queue
            subDivisionSync:
              destination: {{ env}}_license_sub_division_sync
              group: mco-partner-master-service
            onSubDivisionSync:
              destination: {{ env}}_license_sub_division_sync
              group: mco-partner-master-service
            expiringLicensePartnersEvent:
              destination: {{ env }}_expiring_license_partners
            processExpiringLicensePartnersEvent:
              destination: {{ env }}_expiring_license_partners
              group: mco-partner-master-service
            triggerInMemoryCacheEvictEvent:
              destination: {{ env }}_in_memory_cache_evict
            processInMemoryCacheEvictEvent:
              destination: {{ env }}_in_memory_cache_evict
            triggerRefreshPartnerWhPoMappingEvent:
              destination: {{ env }}_refresh_partner_wh_po_mapping
            processRefreshPartnerWhPoMappingEvent:
              destination: {{ env }}_refresh_partner_wh_po_mapping
              group: mco-partner-master-service
            triggerSellerContactDetailUpdateEvent:
              destination: {{ env }}_seller_location_contact_mapping_update
          kafka:
            binder:
              brokers: kafka.scm.gomercury.in:9092
      datasource:
        hikari:
          jdbc-url: jdbc:mysql://mysql-dev.scm.gomercury.in:3306/partner?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
          password: ${DB_PASS}
          username: ${DB_USER}
        url: jdbc:mysql://mysql-dev.scm.gomercury.in:3306/partner?characterEncoding=UTF-8&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      jpa:
        show-sql: false
      redis:
        host: redis-dev.redis.svc.cluster.local
        port: 6379
        database: 1
        connection-timeout: 500
      openapi:
        server:
          url: {{ fqdn }}/{{ project_name }}
          description: Development
      springdoc:
        api-docs:
          path: /api-docs
